class DashCam{
	public static void main(String[] dashcam){
		System.out.println("About IZI Drive Plus 4K Dual Channel DashCam with GPS Navigation,3 FHD Screen, 170° Wide Angle, Night Vision, G-Sensor, WiFi, ADAS, Emergency Recording, Made for Indian Roads, Optional Car Parking Monitor");
		System.out.println("* 4K Dual Channel Dash Cam with Super Sharp Resolution-Experience 170° Wide-angle delivers top-quality 3840x2160P for front camera and 1920x1080P for rear. Capture crystal-clear views, decoding street signs and license plates with ease");
		System.out.println("* 3 UHD LCD Screen powered with Exceptional SONY STARVIS Sensor - Largest and best screen size in its class worldwide ensures meticulous detail capture with pixel-perfect precision. Enhanced by the superior SONY IMX sensor, footage maintains exceptional clarity and top-notch quality even in low light. Your nighttime drives just got better and safer");
		System.out.println("* ADAS Technology with AI powered G-Sensor - Drive with confidence, safeguarded by cutting-edge technology. Precise lane departure warnings, forward collision alerts, and much more. G-Sensor swiftly preserves critical footage in emergencies, Emergency accident lock - automatically locks real-time video segments during collisions or crashes to protect them from deletion");
		System.out.println("* Made for Indian Roads - Built with Supercapacitor and HDR/WDR Offering crystal clear capture up to 45ft, ensures instant operation, durability in extreme temperatures, and reliable performance for effective road recording tailored for Indian Roads and Weather. Secure evidence for insurance claims, disputes, and traffic compliance with confidence");
		System.out.println("* Inbuilt GPS and 24-Hour Parking Surveillance : Every recording captures speed and location data. An optional hardware kit activates Parking Mode, automatically recording hit-and-run collisions for your safety. Swift playback allows quick review of crucial events, ensuring constant vehicle protection");
		System.out.println("* 1 Year Warranty, IZI Drive Official App Connectivity- Link your mobile (iOS/Android) to the IZI Drive Dash Camera, Looprecording Timelapse, WiFi connectivity, Instant Share, resolution adjustment, Speed Limit Alert settings, Live View, Sub-Folder organization, and control options for Automatic Emergency Recording, G-Sensor sensitivity, Dash Camera Volume, and Video Record Length conveniently. Supports Upto 256GB Card");
	}
}